# docker compose --env-file .env.dev up --build -d
# Use this to pass the environment file to the docker compose

networks:
  default:
    driver: bridge

services:
  nodeapi:
    container_name: vanila-api-container
    env_file:
      # - .env
      - ./config/dev.env
      # - ./config/prod.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    command: yarn dev
    depends_on:
      - mongo

  mongo:
    container_name: vanila-mongo-container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

volumes:
  mongodb:
  mongodb_config:
