# docker compose --env-file .env.dev up --build -d
# Use this to pass the environment file to the docker compose

networks:
  default:
    driver: bridge

services:
  vanila-api:
    container_name: vanila-api-container
    build:
      context: .
      dockerfile: Dockerfile
    image: vanila-api:latest
    ports:
      - "4000:3000"
    volumes:
      - .:/app
    command: yarn dev
    depends_on:
      - mongo

  mongo:
    container_name: vanila-mongo-container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

volumes:
  mongodb:
  mongodb_config:
