name: Workflow Test

on:
  workflow_call:
    inputs:
      environment:
          required: true
          type: string
          description: 'Env Value'
      name:
          required: true
          type: string
          description: 'Name'
      value:
          required: true
          type: string
          description: 'Value'
    secrets:
      token:
        required: true        
        description: 'Token'
  
env:
    owner: ${{ github.repository_owner }}
    repo: ${{ github.repository }}    

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create Env Variable (${{ github.repository }})
      run: echo "GITHUB_PROCESS_SHA=PROCESS_$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
    - name: Update environment variables 
      shell: bash
      run: |
        curl --location 'https://api.github.com/repos/${{github.repository}}/environments/${{inputs.environment}}/variables' \
        --header 'Accept: application/vnd.github+json' \
        --header 'Authorization: Bearer ${{ secrets.token }}' \
        --header 'X-GitHub-Api-Version: 2022-11-28' \
        --header 'Content-Type: application/json' \
        --data '{"name":"'$GITHUB_PROCESS_SHA'","value":"'${{ inputs.value }}'"}'
        
  deploy:
    name: Get Env Variable (${{ github.repository }})
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: build
    steps:      
      - uses: actions/checkout@v2
      - name: Create Env Variable (${{ github.repository }})
        run: |
          echo "GITHUB_PROCESS_SHA=PROCESS_$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
          set foo=PROCESS_$(echo $GITHUB_SHA | cut -c 1-6)
          echo "-------------"
          echo $GITHUB_PROCESS_SHA
          echo "-------------"
          echo $GITHUB_SHA
          echo $foo
          echo "-------------"
      - name: Update environment variables 
        shell: bash
        run: |
          set foo=PROCESS_$(echo $GITHUB_SHA | cut -c 1-6)
          response=$(curl --location 'https://api.github.com/repos/${{github.repository}}/environments/${{inputs.environment}}/variables/$foo' \
            --header 'Accept: application/vnd.github+json' \
            --header 'Authorization: Bearer ${{ secrets.token }}' \
            --header 'X-GitHub-Api-Version: 2022-11-28')

          echo $(echo $response | jq -r '.name')
          
      - name: ProcessStep1
        #if: ${{vars.process != 'process'}}
        run: |
          echo "Step1 Process:" #$GITHUB_PROCESS_SHA_VALUE
          #exit 1
      - name: ProcessStep2
        #if: ${{vars.process == 'process'}}
        run: |
          echo "Step2 Process:" ${{ vars.process }}

  # Step2:
  #   name: Step2    
  #   if: step1.outputs.status == 'success'
  #   runs-on: ubuntu-latest
  #   environment: ${{ inputs.environment }}    
  #   needs: Step1
  #   #continue-on-error: true    

  #   steps:
  #     - name: ProcessStep2
  #       run: |
  #         echo "Step2 Process:" ${{ vars.process }}
  