name: Workflow Test

on:
  workflow_call:
    inputs:
      instance:
          required: true
          type: string
          description: 'Instance to plan the infrastructure'

  
jobs:
  azure-login:
    name: Resources Plan Validation
    runs-on: ubuntu-latest
    
    env:
      RESOURCE_GROUP: '${{inputs.instance}}'
      FOO: 'bar$inputs.instance'
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: View Secrets Context
        shell: bash
        run: |
          echo "Foo:" $RESOURCE_GROUP
          echo "Foo:" $FOO
          echo "Foo:" $env.FOO
          echo "Foo:" $env.RESOURCE_GROUP
        