name: Workflow Test

on:
  workflow_call:
    inputs:
      env:
          required: true
          type: string
          description: 'Env Value'
    secrets:
      server:
        required: true        
        description: 'Server to login to'
  
jobs:
  azure-login:
    name: Resources Plan Validation
    runs-on: ubuntu-latest
    
    env:
      FOO: '$FOO'
      ENV: ${{ inputs.env }}
      SERVER: ${{ secrets.server }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: View Secrets Context
        shell: bash
        run: |
          echo "Foo:" $FOO
          echo "Foo:" $env.FOO
          echo "instance:" ${{ inputs.ENV }}
          echo "instance:" ${{ env.ENV }}
          echo "server:" ${{ secrets.server }}
          echo "server:" ${{ env.SERVER }}
          
        