name: Workflow Test

on:
  workflow_call:
    inputs:
      instance:
          required: true
          type: string
          description: 'Instance to plan the infrastructure'
      server:
          required: true
          type: string
          description: 'Server to login to'

  
jobs:
  azure-login:
    name: Resources Plan Validation
    runs-on: ubuntu-latest
    
    env:
      FOO: '$FOO'
      INSTANCE: ${{ inputs.instance }}
      SERVER: ${{ inputs.server }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: View Secrets Context
        shell: bash
        run: |
          echo "Foo:" $FOO
          echo "Foo:" $env.FOO
          echo "instance:" ${{ inputs.instance }}
          echo "instance:" ${{ env.INSTANCE }}
          echo "server:" ${{ inputs.server }}
          echo "server:" ${{ env.SERVER }}
          
        