name: Workflow Test

on:
  workflow_call:
    inputs:
      environment:
          required: true
          type: string
          description: 'Env Value'
      name:
          required: true
          type: string
          description: 'Name'
      value:
          required: true
          type: string
          description: 'Value'
    secrets:
      token:
        required: true        
        description: 'Token'
  
env:
    owner: ${{ github.repository_owner }}
    repo: ${{ github.repository }}    

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
    - name: Test
      run: echo $GITHUB_SHA_SHORT
    - name: Update environment variables - ${{ github.repository }} and owner - ${{ github.repository_owner }}
      #if: ${{inputs.type_var_sec == 'environment' && inputs.type_of_input == 'variable'}}
      shell: bash
      run: |
        curl --location 'https://api.github.com/repos/saga-epm/my-vanila-api/environments/test/variables' \
        --header 'Accept: application/vnd.github+json' \
        --header 'Authorization: Bearer ${{ secrets.token }}' \
        --header 'X-GitHub-Api-Version: 2022-11-28' \
        --header 'Content-Type: application/json' \
        --data '{"name":"USERNAME1","value":"octocat"}'

        # curl -L \
        #   -X PATCH \
        #   -H "Accept: application/vnd.github+json" \
        #   -H "Authorization: Bearer ${{ secrets.token }}"\
        #   -H "X-GitHub-Api-Version: 2022-11-28" \
        #   https://api.github.com/repos/${{ env.owner}}/${{ env.repo }}/environments/${{inputs.environment}}/variables \
        #   -d '{"name":"'${{ inputs.name }}'","value":"'${{ inputs.value }}'"}'

        echo "name=${{ inputs.name }}" >> $GITHUB_OUTPUT
        echo "value=${{ inputs.value }}" >> $GITHUB_OUTPUT        

  # azure-login:
  #   name: Validation
  #   runs-on: ubuntu-latest
  #   environment: ${{ inputs.environment }}
   
  #   env:
  #     SERVER: ${{ secrets.server }}
      
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Process
  #       if: ${{vars.process == 'true'}}
  #       run: |
  #         echo "Validation-Process:" ${{ vars.process }}
     
  step1:
    name: step1
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: build
    steps:      
      - name: ProcessStep1
        if: ${{vars.process != 'process'}}
        run: |
          echo "Step1 Process:" ${{ vars.process }}
          exit 1
      - name: ProcessStep2
        if: ${{vars.process == 'process'}}
        run: |
          echo "Step2 Process:" ${{ vars.process }}

  # Step2:
  #   name: Step2    
  #   if: step1.outputs.status == 'success'
  #   runs-on: ubuntu-latest
  #   environment: ${{ inputs.environment }}    
  #   needs: Step1
  #   #continue-on-error: true    

  #   steps:
  #     - name: ProcessStep2
  #       run: |
  #         echo "Step2 Process:" ${{ vars.process }}
  