name: Workflow Test

env:
  GLOBAL_VAR: 'GlobalValue' # Global environment variable accessible to all jobs and steps

on:
  workflow_call:
    inputs:
      instance:
          required: true
          type: string
          description: 'Instance to plan the infrastructure'

  
jobs:
  azure-login:
    name: Resources Plan Validation
    runs-on: ubuntu-latest
    
    env:
      RESOURCE_GROUP: '${{GLOBAL_VAR}}-${{inputs.instance}}'
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: View Secrets Context
        shell: bash
        run: echo "Foo:" $RESOURCE_GROUP
        