name: Workflow Test

on:
  workflow_call:
    inputs:
      environment:
          required: true
          type: string
          description: 'Env Value'
    secrets:
      server:
        required: true        
        description: 'Server to login to'
  
jobs:
  azure-login:
    name: Resources Plan Validation
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
   
    env:
      FOO: '$FOO'
      ENV: ${{ inputs.environment }}
      SERVER: ${{ secrets.server }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Process
        if: ${{ vars.process }} == 'true'
        run: |
          echo "Process:" ${{ vars.process }}

      - name: View Secrets Context
        shell: bash
        run: |
          # echo "Fooo:" $FOO
          # echo "Foo:" $env.FOO
          # echo "instance:" ${{ inputs.ENV }}
          # echo "instance:" ${{ env.ENV }}
          echo "server:" ${{ secrets.server }} | sed 's/./& /g'
          # echo "server:" ${{ env.SERVER }}

  check-step:
    name: Check Process Step
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: azure-login

    steps:
      - name: Process
        if: ${{ vars.process }} != 'true'
        run: |
          echo "Process Failed:" ${{ vars.process }}
          exit 1

  re-process-step:
    name: Re-Process Step
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: check-step
    if: ${{ vars.process }} == 'true'

    steps:
      - name: Process        
        run: |
          echo "Re-Process Step:" ${{ vars.process }}          
          
        