name: Workflow Test

on:
  workflow_call:
    inputs:
      instance:
          required: true
          type: string
          description: 'Instance to plan the infrastructure'

  
jobs:
  azure-login:
    name: Resources Plan Validation
    runs-on: ubuntu-latest
    
    env:
      FOO: 'foo$inputs.instance'
      BOO: 'boo$env.FOO'
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: View Secrets Context
        shell: bash
        run: |
          echo "Foo:" $FOO
          echo "Foo:" $BOO
          
        